import { ProductionTable } from '../shared/types';

export function getProductionTables(): ProductionTable[] {
  return [
    {
      name: 'AAH-AUTH_AGENT_HOLD',
      id: 1,
      data: [
        {
          status: 'Production',
          row_no: 9,
          service_group: 1,
          auth_agent_type: '',
          auth_agent_name: '',
          auth_agent_id: '',
          auth_agent_mail_code: '',
          auth_agent_phone: '',
          agency_code: 324,
          program_on_hold: 'N',
          hold_begin_date: '',
          hold_end_date: '',
          contract_cap_check: '',
          comments: 'SSAS INITIAL LOAD',
          active: 'A',
        },
        {
          status: 'Production',
          row_no: 4,
          service_group: 2,
          auth_agent_type: 'CM',
          auth_agent_name: 'CLASS Operations',
          auth_agent_id: '2-PM',
          auth_agent_mail_code: 'W-521',
          auth_agent_phone: '512-438-4512',
          agency_code: 324,
          program_on_hold: 'Y',
          hold_begin_date: '12/31/9999',
          hold_end_date: '12/31/9999',
          contract_cap_check: 'N',
          comments: 'SSAS INITIAL LOAD',
          active: 'A',
        },
        {
          status: 'Production',
          row_no: 1,
          service_group: 4,
          auth_agent_type: 'CM',
          auth_agent_name: 'SSLC Program Manager',
          auth_agent_id: '4-PM',
          auth_agent_mail_code: '',
          auth_agent_phone: '',
          agency_code: 655,
          program_on_hold: 'N',
          hold_begin_date: '',
          hold_end_date: '',
          contract_cap_check: 'N',
          comments: 'SSAS INITIAL LOAD',
          active: 'A',
        },
      ],
    },
    {
      name: 'CAP-CAP_THRESHOLD',
      id: 2,
      data: [
        {
          status: 'Production',
          row_no: 1,
          service_group: 21,
          cap_id: 'SV5',
          cap_type: 'SV',
          level_of_service: '',
          service_codes: '5A',
          begin_date: '02/01/2012',
          end_date: '12/31/2199',
          limit_type: 1,
          state_threshold: 0.0,
          coach_threshold: 2118.86,
          percent_200_threshold: 9999999.99,
          life_time_cap_met: '',
          age_limit_type: 3,
          range_limitation_service_code: '',
          range_lower_limit: '',
          range_upper_limit: '',
          active: 'A',
          create_date: '04/02/2012',
          create_by: 'SSAS',
          update_date: '',
          update_by: '',
          comments: 'SSAS INITIAL LOAD',
          tmhp_flag: '',
          threshold_indicator: 'N',
        },
        {
          status: 'Production',
          row_no: 2,
          service_group: 21,
          cap_id: 'SV6',
          cap_type: 'SV',
          level_of_service: '',
          service_codes: '5A',
          begin_date: '02/01/2012',
          end_date: '12/31/2199',
          limit_type: 1,
          state_threshold: 2000.0,
          coach_threshold: 2118.86,
          percent_200_threshold: 9999999.99,
          life_time_cap_met: '',
          age_limit_type: 4,
          range_limitation_service_code: '',
          range_lower_limit: '',
          range_upper_limit: '',
          active: 'A',
          create_date: '04/02/2012',
          create_by: 'SSAS',
          update_date: '',
          update_by: '',
          comments: 'SSAS INITIAL LOAD',
          tmhp_flag: '',
          threshold_indicator: 'N',
        },
      ],
    },
    {
      name: 'CF1-BILLING CODE',
      id: 3,
      data: [
        {
          id: 1,
          row_no: 1,
          billing_code: '#####',
          description: 'VALID HCPCS CODE (PLACE HOLDER ENTRY)',
          atypical_indicator: 'Y',
          active: 'A',
          begin_date: '01/01/1900',
          end_date: '12/31/2199',
          create_date: '10/21/2007',
          create_by: 'CODETABLE',
          update_date: '10/21/2007',
          update_by: 'CODETABLE',
          comments: '',
          status: 'Production',
        },
        {
          id: 3,
          row_no: 2,
          billing_code: 'C0100',
          description: 'HOME DELIVERED MEALS',
          atypical_indicator: 'N',
          active: 'A',
          begin_date: '09/01/1998',
          end_date: '12/31/2199',
          create_date: '10/21/2007',
          create_by: 'CODETABLE',
          update_date: '10/21/2007',
          update_by: 'CODETABLE',
          comments: '',
          status: 'Production',
        },
        {
          id: 4,
          row_no: 3,
          billing_code: 'C0101',
          description: 'TITLE XIX CBA MEALS',
          atypical_indicator: 'N',
          active: 'A',
          begin_date: '09/01/2001',
          end_date: '12/31/2199',
          create_date: '10/21/2007',
          create_by: 'CODETABLE',
          update_date: '10/21/2007',
          update_by: 'CODETABLE',
          comments: '',
          status: 'Production',
        },
      ],
    },
    {
      name: 'CFB- BILLING COMBINATION',
      id: 4,
      data: [
        {
          status: 'Production',
          row_no: 1,
          service_group: 1,
          billing_code: 'C0402',
          active: 'A',
          fund_code: 100,
          service_code: 50,
          fed_type_of_service: 7,
          mi_record_type: 57,
          level_of_service_type: '',
          level_of_service: '',
          begin_date: '09/23/1998',
          end_date: '12/31/2199',
          create_date: '10/22/2007',
          create_by: 'CODETABLE',
          update_date: '02/13/1999',
          update_by: 'CODETABLE',
          comments: '',
        },
        {
          status: 'Production',
          row_no: 2,
          service_group: 1,
          billing_code: 'G0446',
          active: 'A',
          fund_code: 19,
          service_code: 7,
          fed_type_of_service: 80,
          mi_record_type: 122,
          level_of_service_type: '',
          level_of_service: '',
          begin_date: '09/23/1998',
          end_date: '10/15/2003',
          create_date: '10/22/2007',
          create_by: 'CODETABLE',
          update_date: '02/13/1999',
          update_by: 'CODETABLE',
          comments: 'Ended: replaced by SC 7A',
        },
        {
          status: 'Production',
          row_no: 3,
          service_group: 1,
          billing_code: 'G0447',
          active: 'A',
          fund_code: 19,
          service_code: 7,
          fed_type_of_service: 80,
          mi_record_type: 122,
          level_of_service_type: '',
          level_of_service: '',
          begin_date: '09/23/1998',
          end_date: '10/15/2003',
          create_date: '10/22/2007',
          create_by: 'CODETABLE',
          update_date: '02/13/1999',
          update_by: 'CODETABLE',
          comments: 'Ended: replaced by SC 7A',
        },
      ],
    },
    {
      name: 'CFI-ITEM CODE',
      id: 5,
      data: [
        {
          status: 'Production',
          row_no: 1,
          item_code: 4,
          description: 'FEEDING',
          active: 'A',
          begin_date: '01/01/1900',
          end_date: '12/31/2199',
          create_date: '10/20/2007',
          create_by: 'CODETABLE',
          update_date: '10/20/2007',
          update_by: 'CODETABLE',
          comments: '',
        },
        {
          status: 'Production',
          row_no: 2,
          item_code: 5,
          description: 'GROOMING',
          active: 'A',
          begin_date: '01/01/1900',
          end_date: '12/31/2199',
          create_date: '10/20/2007',
          create_by: 'CODETABLE',
          update_date: '10/20/2007',
          update_by: 'CODETABLE',
          comments: '',
        },
        {
          status: 'Production',
          row_no: 3,
          item_code: 6,
          description: 'ROUTINE HAIR/SKIN CARE',
          active: 'A',
          begin_date: '01/01/1900',
          end_date: '12/31/2199',
          create_date: '10/20/2007',
          create_by: 'CODETABLE',
          update_date: '10/20/2007',
          update_by: 'CODETABLE',
          comments: '',
        },
      ],
    },
    {
      name: 'CFM- ELIGIBILITY COMBINATION',
      id: 6,
      data: [
        {
          status: 'Production',
          row_no: 1,
          service_group: 1,
          service_code: 1,
          'client_pgm._type_cd.': 1,
          'comb._cvrg._cd.': 'P',
          'elig._catg._serv._cd.': 2,
          fund_code: 19,
          active: 'A',
          begin_date: '01/01/1960',
          end_date: '12/31/2199',
          create_date: '10/25/2007',
          create_by: 'CODETABLE',
          update_date: '10/25/2007',
          update_by: 'CODETABLE',
          comments: '',
        },
        {
          status: 'Production',
          row_no: 2,
          service_group: 1,
          service_code: 1,
          'client_pgm._type_cd.': 1,
          'comb._cvrg._cd.': 'R',
          'elig._catg._serv._cd.': 2,
          fund_code: 19,
          active: 'A',
          begin_date: '01/01/1960',
          end_date: '12/31/2199',
          create_date: '10/25/2007',
          create_by: 'CODETABLE',
          update_date: '10/25/2007',
          update_by: 'CODETABLE',
          comments: '',
        },
      ],
    },
    {
      name: 'CFP-PROCEDURE CODE',
      id: 7,
      data: [
        {
          status: 'Production',
          row_no: 1,
          procedure_code: 36489,
          description: 'PLACEMENT CENTRAL VENOUS CATH PERCUTANEOUS-OVER AGE 2',
          'tooth_id_ind.': 'N',
          active: 'A',
          begin_date: '01/01/1900',
          end_date: '12/31/2199',
          create_date: '10/20/2007',
          create_by: 'CODETABLE',
          update_date: '10/20/2007',
          update_by: 'CODETABLE',
          comments: '',
        },
        {
          status: 'Production',
          row_no: 2,
          procedure_code: 36533,
          description:
            'INSERTION OF IMPLANTABLE VENOUS ACCESS PORT WITH OR WITHOUT SUBCUTANEOUS RESERVO',
          'tooth_id_ind.': 'N',
          active: 'A',
          begin_date: '01/01/1900',
          end_date: '12/31/2199',
          create_date: '10/20/2007',
          create_by: 'CODETABLE',
          update_date: '10/20/2007',
          update_by: 'CODETABLE',
          comments: '',
        },
        {
          status: 'Production',
          row_no: 3,
          procedure_code: 36535,
          description: 'REMOVAL OF ACCESS DEVICE',
          'tooth_id_ind.': 'N',
          active: 'A',
          begin_date: '01/01/1900',
          end_date: '12/31/2199',
          create_date: '10/20/2007',
          create_by: 'CODETABLE',
          update_date: '10/20/2007',
          update_by: 'CODETABLE',
          comments: '',
        },
      ],
    },
    {
      name: 'CFR-PROCEDURE CODE RATE',
      id: 8,
      data: [
        {
          status: 'Production',
          row_no: 1,
          procedure_code: 36489,
          unit_rate: 70.94,
          active: 'A',
          begin_date: '01/01/1985',
          end_date: '08/31/1999',
          create_date: '10/20/2007',
          create_by: 'CODETABLE',
          update_date: '03/12/2004',
          update_by: 'CODETABLE',
          comments: '',
        },
        {
          status: 'Production',
          row_no: 2,
          procedure_code: 36489,
          unit_rate: 72.01,
          active: 'A',
          begin_date: '09/01/1999',
          end_date: '07/31/2004',
          create_date: '10/20/2007',
          create_by: 'CODETABLE',
          update_date: '07/17/2004',
          update_by: 'CODETABLE',
          comments: '',
        },
        {
          status: 'Production',
          row_no: 3,
          procedure_code: 36533,
          unit_rate: 212.57,
          active: 'A',
          begin_date: '04/01/1992',
          end_date: '08/31/1999',
          create_date: '10/20/2007',
          create_by: 'CODETABLE',
          update_date: '08/21/2001',
          update_by: 'CODETABLE',
          comments: '',
        },
      ],
    },
    {
      name: 'CLC-LVL OF SRVC GRP CROSS REF',
      id: 9,
      data: [
        {
          status: 'Production',
          row_no: 1,
          service_group: 4,
          service_code: 1,
          level_type: 'LC',
          active: 'A',
          begin_date: '09/01/1995',
          end_date: '12/31/2199',
          create_date: '10/20/2007',
          create_by: 'CODETABLE',
          update_date: '10/20/2007',
          update_by: 'CODETABLE',
          comments: '',
        },
        {
          status: 'Production',
          row_no: 2,
          service_group: 5,
          service_code: 1,
          level_type: 'LC',
          active: 'A',
          begin_date: '09/01/1995',
          end_date: '12/31/2199',
          create_date: '10/20/2007',
          create_by: 'CODETABLE',
          update_date: '10/20/2007',
          update_by: 'CODETABLE',
          comments: '',
        },
        {
          status: 'Production',
          row_no: 3,
          service_group: 6,
          service_code: 1,
          level_type: 'LN',
          active: 'A',
          begin_date: '01/01/1997',
          end_date: '12/31/2199',
          create_date: '10/20/2007',
          create_by: 'CODETABLE',
          update_date: '10/20/2007',
          update_by: 'CODETABLE',
          comments: '',
        },
      ],
    },
    {
      name: 'CLS - LEVEL OF SERVICE',
      id: 10,
      data: [
        {
          status: 'Production',
          row_no: 1,
          level_type: 20,
          level_of_service: 1,
          active: 'A',
          begin_date: '01/01/1900',
          end_date: '12/31/2199',
          create_date: '10/21/2007',
          create_by: 'CODETABLE',
          update_date: '08/25/1999',
          update_by: 'CODETABLE',
          comments: '',
        },
        {
          status: 'Production',
          row_no: 2,
          level_type: 20,
          level_of_service: 10,
          active: 'A',
          begin_date: '01/01/1900',
          end_date: '12/31/2199',
          create_date: '10/21/2007',
          create_by: 'CODETABLE',
          update_date: '08/25/1999',
          update_by: 'CODETABLE',
          comments: '',
        },
        {
          status: 'Production',
          row_no: 3,
          level_type: 20,
          level_of_service: 11,
          active: 'A',
          begin_date: '01/01/1900',
          end_date: '12/31/2199',
          create_date: '10/21/2007',
          create_by: 'CODETABLE',
          update_date: '08/25/1999',
          update_by: 'CODETABLE',
          comments: '',
        },
      ],
    },
    {
      name: 'CMD - MODIFIER',
      id: 11,
      data: [
        {
          status: 'Production',
          row_no: 1,
          modifier_code: 'A1',
          description: 'DRESSING FOR ONE WOUND',
          active: 'A',
          begin_date: '01/01/1900',
          end_date: '12/31/2199',
          create_date: '10/20/2007',
          create_by: 'CODETABLE',
          update_date: '10/20/2007',
          update_by: 'CODETABLE',
          comments: '',
        },
        {
          status: 'Production',
          row_no: 2,
          modifier_code: 'A2',
          description: 'DRESSING FOR TWO WOUNDS',
          active: 'A',
          begin_date: '01/01/1900',
          end_date: '12/31/2199',
          create_date: '10/20/2007',
          create_by: 'CODETABLE',
          update_date: '10/20/2007',
          update_by: 'CODETABLE',
          comments: '',
        },
        {
          status: 'Production',
          row_no: 3,
          modifier_code: 'A3',
          description: 'DRESSING FOR THREE WOUNDS',
          active: 'A',
          begin_date: '01/01/1900',
          end_date: '12/31/2199',
          create_date: '10/20/2007',
          create_by: 'CODETABLE',
          update_date: '10/20/2007',
          update_by: 'CODETABLE',
          comments: '',
        },
      ],
    },
    {
      name: 'CMR - MODIFIER CROSS REFERENCE',
      id: 12,
      data: [
        {
          status: 'Production',
          row_no: 1,
          modifier_location: 1,
          modifier_code: 'U1',
          modifier_result_value: 1,
          modifier_rule_code: 1,
          modifier_cross_walk_value: '',
          description: 'SERVICE GROUP 1',
          active: 'A',
          begin_date: '01/01/1900',
          end_date: '12/31/2199',
          create_date: '10/20/2007',
          create_by: 'CODETABLE',
          update_date: '10/20/2007',
          update_by: 'CODETABLE',
          comments: '',
        },
        {
          status: 'Production',
          row_no: 2,
          modifier_location: 1,
          modifier_code: 'U2',
          modifier_result_value: 2,
          modifier_rule_code: 1,
          modifier_cross_walk_value: '',
          description: 'SERVICE GROUP 2',
          active: 'A',
          begin_date: '01/01/1900',
          end_date: '12/31/2199',
          create_date: '10/20/2007',
          create_by: 'CODETABLE',
          update_date: '10/20/2007',
          update_by: 'CODETABLE',
          comments: '',
        },
        {
          status: 'Production',
          row_no: 3,
          modifier_location: 1,
          modifier_code: 'U3',
          modifier_result_value: 3,
          modifier_rule_code: 1,
          modifier_cross_walk_value: '',
          description: 'SERVICE GROUP 3',
          active: 'A',
          begin_date: '01/01/1900',
          end_date: '12/31/2199',
          create_date: '10/20/2007',
          create_by: 'CODETABLE',
          update_date: '10/20/2007',
          update_by: 'CODETABLE',
          comments: '',
        },
      ],
    },
    {
      name: 'CNB-BILL CODE CROSSWALK',
      id: 13,
      data: [
        {
          status: 'Production',
          row_no: 1,
          service_group: 3,
          bill_code: 'RG929',
          description: ' AL RESIDENTIAL CARE - NON APT (LEVEL 5) PB2',
          service_code: '19B',
          level_type: 'CR',
          level_value: 'PB2',
          proc_cd_qual: 'HC',
          hcpcs_code: 'T2031',
          cpt_code: '',
          revenue_code: '',
          pos: '',
          mod1: 'U2',
          mod2: 'U2',
          mod3: '',
          mod4: '',
          claim_fil_ind: '',
          claim_type: 'P',
          active: 'A',
          begin_date: '09/01/2008',
          end_date: '12/31/2199',
          create_date: '11/10/2009',
          create_by: '00000105317',
          update_date: '12/03/2019',
          update_by: 'CODE TABLE',
          comments: '',
        },
        {
          status: 'Production',
          row_no: 2,
          service_group: 1,
          bill_code: 'V0200',
          description: 'VA DAILY CARE WITH ADD ON',
          service_code: '1',
          level_type: '',
          level_value: '',
          proc_cd_qual: '',
          hcpcs_code: '',
          cpt_code: '',
          revenue_code: '',
          pos: '',
          mod1: '',
          mod2: '',
          mod3: '',
          mod4: '',
          claim_fil_ind: '',
          claim_type: '',
          active: 'A',
          begin_date: '01/01/1900',
          end_date: '08/31/2003',
          create_date: '10/23/2007',
          create_by: 'CODE TABLE',
          update_date: '06/30/2003',
          update_by: 'CODETABLE',
          comments:
            'THP - Removed VA indicator.  Combo is ended and therefore not needed.',
        },
      ],
    },
    {
      name: 'CNP - NATIONAL PROCEDURE CODES',
      id: 14,
      data: [
        {
          status: 'Production',
          row_no: 1,
          national_procedure_code: 'D0501',
          description: 'HISTOPATHOLOGIC EXAMINATIONS',
          active: 'A',
          code_type: 'AD',
          begin_date: '01/01/2003',
          end_date: '12/31/2005',
          create_date: '10/21/2007',
          create_by: 'CODETABLE',
          update_date: '02/01/2006',
          update_by: 'CODETABLE',
          comments: '',
        },
        {
          status: 'Production',
          row_no: 2,
          national_procedure_code: 'D1201',
          description: 'TOPICAL FLUOR W PROPHY CHILD',
          active: 'A',
          code_type: 'AD',
          begin_date: '01/01/1996',
          end_date: '12/31/2006',
          create_date: '10/21/2007',
          create_by: 'CODETABLE',
          update_date: '01/31/2007',
          update_by: 'CODETABLE',
          comments: '',
        },
      ],
    },
    {
      name: 'CNS - CMS NATIONAL CODES',
      id: 15,
      data: [
        {
          status: 'Production',
          row_no: 1,
          'national_proc._code': 'D0140',
          revenue_code: '',
          active: 'A',
          begin_date: '01/01/1900',
          end_date: '12/31/2199',
          create_date: '10/21/2007',
          create_by: 'CODETABLE',
          update_date: '10/16/2003',
          update_by: 'CODETABLE',
          comments: '',
        },
        {
          status: 'Production',
          row_no: 2,
          'national_proc._code': 'D9110',
          revenue_code: '',
          active: 'A',
          begin_date: '01/01/1900',
          end_date: '12/31/2199',
          create_date: '10/21/2007',
          create_by: 'CODETABLE',
          update_date: '10/16/2003',
          update_by: 'CODETABLE',
          comments: '',
        },
      ],
    },
    {
      name: 'COV - COVERAGE CODE',
      id: 16,
      data: [
        {
          status: 'Production',
          row_no: 1,
          coverage_code: '1',
          description: 'TITLE XX',
          active: 'A',
          begin_date: '01/01/1900',
          end_date: '12/31/2199',
          create_date: '10/20/2007',
          create_by: 'CODETABLE',
          update_date: '01/05/1998',
          update_by: 'CODETABLE',
          send_to_ref_code: 'Y',
          comments: '',
        },
        {
          status: 'Production',
          row_no: 2,
          coverage_code: 'A',
          description: 'BELOW AFDC STANDARDS',
          active: 'A',
          begin_date: '01/01/1900',
          end_date: '12/31/2199',
          create_date: '10/20/2007',
          create_by: 'CODETABLE',
          update_date: '08/10/2007',
          update_by: 'CODETABLE',
          send_to_ref_code: 'N',
          comments: '',
        },
      ],
    },
    {
      name: 'CPQ - PROCEDURE CODE QUALIFIER',
      id: 17,
      data: [
        {
          status: 'Production',
          row_no: 1,
          qualifier_code: 'AD',
          description: 'ADA',
          active: 'A',
          begin_date: '01/01/1900',
          end_date: '12/31/2199',
          create_date: '10/20/2007',
          create_by: 'CODETABLE',
          update_date: '10/20/2007',
          update_by: 'CODETABLE',
          comments: '',
        },
        {
          status: 'Production',
          row_no: 2,
          qualifier_code: 'HC',
          description: 'HCPCS/CPT',
          active: 'A',
          begin_date: '01/01/1900',
          end_date: '12/31/2199',
          create_date: '10/20/2007',
          create_by: 'CODETABLE',
          update_date: '10/20/2007',
          update_by: 'CODETABLE',
          comments: '',
        },
      ],
    },
    {
      name: 'CPS - PLACE OF SERVICE',
      id: 18,
      data: [
        {
          status: 'Production',
          row_no: 1,
          pos_code: 3,
          description: 'SCHOOL',
          active: 'A',
          begin_date: '01/01/1900',
          end_date: '12/31/2199',
          create_date: '10/19/2007',
          create_by: 'CODETABLE',
          update_date: '10/19/2007',
          update_by: 'CODETABLE',
          comments: '',
        },
        {
          status: 'Production',
          row_no: 2,
          pos_code: 4,
          description: 'HOMELESS SHELTER',
          active: 'A',
          begin_date: '01/01/1900',
          end_date: '12/31/2199',
          create_date: '10/19/2007',
          create_by: 'CODETABLE',
          update_date: '10/19/2007',
          update_by: 'CODETABLE',
          comments: '',
        },
      ],
    },
    {
      name: 'CPT - CLIENT PROGRAM TYPE',
      id: 19,
      data: [
        {
          status: 'Production',
          row_no: 1,
          program_type_code: 1,
          description: 'TEST CODE FOR ELIG FILE',
          active: 'A',
          begin_date: '01/01/1900',
          end_date: '12/31/2199',
          create_date: '10/19/2007',
          create_by: 'CODETABLE',
          update_date: '10/19/2007',
          update_by: 'CODETABLE',
          send_to_ref_code: 'N',
          comments: '',
        },
        {
          status: 'Production',
          row_no: 2,
          program_type_code: 2,
          description: 'ATFEL',
          active: 'A',
          begin_date: '01/01/1900',
          end_date: '12/31/2199',
          create_date: '10/19/2007',
          create_by: 'CODETABLE',
          update_date: '10/19/2007',
          update_by: 'CODETABLE',
          send_to_ref_code: 'N',
          comments: '',
        },
      ],
    },
    {
      name: 'CRC- REVENUE CODES',
      id: 20,
      data: [
        {
          status: 'Production',
          row_no: 1,
          revenue_code: 20,
          description: 'RESERVED',
          active: 'A',
          begin_date: '03/01/1963',
          end_date: '12/31/2199',
          create_date: '10/21/2007',
          create_by: 'CODETABLE',
          update_date: '10/16/2003',
          update_by: 'CODETABLE',
          comments: '',
        },
        {
          status: 'Production',
          row_no: 2,
          revenue_code: 21,
          description: 'RESERVED',
          active: 'A',
          begin_date: '03/01/1963',
          end_date: '12/31/2199',
          create_date: '10/21/2007',
          create_by: 'CODETABLE',
          update_date: '10/16/2003',
          update_by: 'CODETABLE',
          comments: '',
        },
      ],
    },
    {
      name: 'CSG - SERVICE GROUP',
      id: 21,
      data: [
        {
          status: 'Production',
          row_no: 1,
          service_group: 1,
          description: 'NURSING FACILITY',
          'agency_cd.': 324,
          active: 'A',
          begin_date: '01/01/1900',
          end_date: '12/31/2199',
          create_date: '10/20/2007',
          create_by: 'CODETABLE',
          update_date: '05/19/1998',
          update_by: 'CODETABLE',
          comments: '',
          send_to_tmhp: 'Y',
        },
        {
          status: 'Production',
          row_no: 2,
          service_group: 10,
          description: 'SWING BEDS',
          'agency_cd.': 324,
          active: 'A',
          begin_date: '01/01/1900',
          end_date: '12/31/2199',
          create_date: '10/20/2007',
          create_by: 'CODETABLE',
          update_date: '05/19/1998',
          update_by: 'CODETABLE',
          comments: '',
          send_to_tmhp: 'Y',
        },
      ],
    },
    {
      name: 'CSI - SERVICE CODE ITEM REC',
      id: 22,
      data: [
        {
          status: 'Production',
          row_no: 1,
          service_code: 15,
          item_code: '5132X',
          active: 'A',
          begin_date: '01/01/1900',
          end_date: '12/31/2199',
          create_date: '10/19/2007',
          create_by: 'CODETABLE',
          update_date: '06/09/1998',
          update_by: 'CODETABLE',
          comments: '',
        },
        {
          status: 'Production',
          row_no: 2,
          service_code: 15,
          item_code: '5135X',
          active: 'A',
          begin_date: '01/01/1900',
          end_date: '12/31/2199',
          create_date: '10/19/2007',
          create_by: 'CODETABLE',
          update_date: '06/09/1998',
          update_by: 'CODETABLE',
          comments: '',
        },
      ],
    },
    {
      name: 'CSP - SERVICE CODE PROCEDURE',
      id: 23,
      data: [
        {
          status: 'Production',
          row_no: 1,
          service_code: 30,
          procedure_code: 36489,
          active: 'A',
          begin_date: '01/01/1900',
          end_date: '12/31/2199',
          create_date: '10/19/2007',
          create_by: 'CODETABLE',
          update_date: '04/26/2001',
          update_by: 'CODETABLE',
          comments: '',
        },
        {
          status: 'Production',
          row_no: 2,
          service_code: 30,
          procedure_code: 36533,
          active: 'A',
          begin_date: '01/01/1900',
          end_date: '12/31/2199',
          create_date: '10/19/2007',
          create_by: 'CODETABLE',
          update_date: '05/19/1998',
          update_by: 'CODETABLE',
          comments: '',
        },
      ],
    },
    {
      name: 'CSR - SERVICE CODE',
      id: 24,
      data: [
        {
          status: 'Production',
          row_no: 1,
          service_code: 1,
          description: 'DAILY CARE',
          active: 'A',
          system_designator: '  ',
          begin_date: '01/01/1900',
          end_date: '12/31/2199',
          create_date: '10/21/2007',
          create_by: 'CODETABLE',
          update_date: '10/21/2007',
          update_by: 'CODETABLE',
          comments: ' ',
          send_to_tmhp: 'Y',
        },
        {
          status: 'Production',
          row_no: 2,
          service_code: 2,
          description: 'SKILLED DAILY CARE',
          active: 'C',
          system_designator: 'NE',
          begin_date: '01/01/1900',
          end_date: '12/31/2199',
          create_date: '10/21/2007',
          create_by: 'CODETABLE',
          update_date: '10/21/2007',
          update_by: 'CODETABLE',
          comments: ' ADDED TO MGREFCDS FROM NEREFCDS - 06/04/2007',
          send_to_tmhp: 'Y',
        },
      ],
    },
    {
      name: 'CSS - SERVICE GRP SERVICE CD',
      id: 25,
      data: [
        {
          status: 'Production',
          row_no: 1,
          service_group: 1,
          service_code: 1,
          active: 'A',
          expedited_unit_rate: 0.0,
          'hourly_ind.': 'N',
          'ai/cp_ind.': 'A',
          'hospice_ind.': 'N',
          'nat._ind.': 'N',
          'one_day_overlap_ind.': 'Y',
          per_auth_limit_code: '',
          unit_type: 5,
          'hospice_rate_ind.': 'N',
          'mesav_service_grp.': '',
          begin_date: '01/01/1900',
          end_date: '12/31/2199',
          create_date: '10/23/2007',
          create_by: 'CODETABLE',
          update_date: '02/20/2001',
          update_by: 'CODETABLE',
          comments: '',
        },
        {
          status: 'Production',
          row_no: 2,
          service_group: 1,
          service_code: 15,
          active: 'A',
          expedited_unit_rate: 0.0,
          'hourly_ind.': 'N',
          'ai/cp_ind.': '',
          'hospice_ind.': 'N',
          'nat._ind.': 'N',
          'one_day_overlap_ind.': 'Y',
          per_auth_limit_code: '',
          unit_type: 4,
          'hospice_rate_ind.': 'N',
          'mesav_service_grp.': '',
          begin_date: '01/01/1900',
          end_date: '12/31/2199',
          create_date: '10/23/2007',
          create_by: 'CODETABLE',
          update_date: '02/20/2001',
          update_by: 'CODETABLE',
          comments: '',
        },
      ],
    },
    {
      name: 'DA2 - SERVICE AUTH EDITS',
      id: 26,
      data: [
        {
          status: 'Production',
          row_no: 1,
          service_group: 1,
          service_code: 3,
          active: 'A',
          maximum_units: 1.0,
          unit_type: 5,
          level_type: '',
          level_value: '',
          level_date_check: '',
          enroll_flag: 2,
          enroll_date_check: 'D',
          isp_flag: 0,
          isp_date_check: '',
          diag_flag: 0,
          diag_date_check: '',
          mnc_flag: 0,
          mnc_date_check: '',
          api_copay_type: 'AI',
          api_copay_date_check: 'D',
          asgn_flag: '',
          asgn_date_check: '',
          mov_flag: '',
          mov_date_check: '',
          force: 'N',
          meaning: 'ECF',
          begin_date: '09/01/1990',
          end_date: '12/31/2199',
          create_date: '10/21/2007',
          create_by: 'CODETABLE',
          update_date: '10/21/2007',
          update_by: 'CODETABLE',
          comments: '',
        },
        {
          status: 'Production',
          row_no: 2,
          service_group: 1,
          service_code: 4,
          active: 'A',
          maximum_units: 1.0,
          unit_type: 5,
          level_type: '',
          level_value: '',
          level_date_check: '',
          enroll_flag: 2,
          enroll_date_check: 'A',
          isp_flag: 0,
          isp_date_check: '',
          diag_flag: 1,
          diag_date_check: 'A',
          mnc_flag: 0,
          mnc_date_check: '',
          api_copay_type: '',
          api_copay_date_check: '',
          asgn_flag: '',
          asgn_date_check: '',
          mov_flag: '',
          mov_date_check: '',
          force: 'N',
          meaning: 'VENTILATOR(S)',
          begin_date: '09/01/1990',
          end_date: '12/31/2199',
          create_date: '10/21/2007',
          create_by: 'CODETABLE',
          update_date: '10/21/2007',
          update_by: 'CODETABLE',
          comments: '',
        },
      ],
    },
    {
      name: 'DA3 - NE SERV EDITS',
      id: 27,
      data: [
        {
          status: 'Production',
          row_no: 1,
          service_group: 1,
          service_code: 3,
          active: 'A',
          designated_direct_services_check: '',
          check_box2: '',
          check_box3: '',
          sort_sequence: 1,
          vfi_flag: 'N',
          begin_date: '09/01/1990',
          end_date: '12/31/2199',
          create_date: '10/21/2007',
          create_by: 'JDG',
          update_date: '12/13/2001',
          update_by: 'MEL',
          comments: '',
        },
        {
          status: 'Production',
          row_no: 2,
          service_group: 1,
          service_code: 1,
          active: 'A',
          designated_direct_services_check: '',
          check_box2: '',
          check_box3: '',
          sort_sequence: 2,
          vfi_flag: 'N',
          begin_date: '09/01/1990',
          end_date: '12/31/2199',
          create_date: '10/21/2007',
          create_by: 'JDG',
          update_date: '12/13/2001',
          update_by: 'MEL',
          comments: '',
        },
      ],
    },
    {
      name: 'DAD - REFERENCE CODES',
      id: 28,
      data: [
        {
          status: 'Production',
          row_no: 1,
          dad_type: 'ACTIONFLAG',
          code: 'A',
          description: 'ADD',
          system_designator: 'MG',
          type_xref: '',
          sort_order: 0,
          active: 'A',
          begin_date: '01/01/1900',
          end_date: '12/31/2199',
          create_date: '06/04/2007',
          create_by: 'CODE TABLE',
          update_date: '06/04/2007',
          update_by: 'JDG',
          send_to_tmhp: 'N',
          comments: '',
        },
        {
          status: 'Production',
          row_no: 2,
          dad_type: 'ACTIONFLAG',
          code: 'N',
          description: 'NEW',
          system_designator: 'NH',
          type_xref: '',
          sort_order: 0,
          active: 'A',
          begin_date: '01/01/1900',
          end_date: '12/31/2199',
          create_date: '06/04/2007',
          create_by: 'CODE TABLE',
          update_date: '06/04/2007',
          update_by: 'JDG',
          send_to_tmhp: 'N',
          comments: '',
        },
      ],
    },
    {
      name: 'DCE - TMHP DUPLICATE CLAIM EDIT',
      id: 29,
      data: [
        {
          status: 'Production',
          row_no: 1,
          service_group: 1,
          service_code: 15,
          procedure_item_indicator: 'Y',
          tooth_id_indicator: 'N',
          begin_date: '01/01/1900',
          end_date: '12/31/2199',
          create_date: '10/19/2007',
          created_by: '',
          update_date: '10/19/2007',
          updated_by: '',
          comments: '',
        },
        {
          status: 'Production',
          row_no: 2,
          service_group: 1,
          service_code: 5,
          procedure_item_indicator: 'Y',
          tooth_id_indicator: 'Y',
          begin_date: '01/01/1900',
          end_date: '12/31/2199',
          create_date: '10/19/2007',
          created_by: '',
          update_date: '10/19/2007',
          updated_by: '',
          comments: '',
        },
      ],
    },
    {
      name: 'DIA - DIAGNOSIS',
      id: 30,
      data: [
        {
          status: 'Production',
          row_no: 1,
          diagnosis_code: 2,
          description: 'DUMMY - TEST DIAGNOSIS',
          version: 9,
          begin_date: '04/01/1991',
          end_date: '12/31/2015',
          active: 'A',
          tmhp_flag: '',
          rc_flag: '',
          hospice_flag: '',
          dms_flag: '',
          idd_flag: '',
          comments: 'SSAS INITIAL LOAD',
          create_date: '03/22/2012',
          create_by: 'SSAS',
          update_date: '',
          update_by: '',
        },
        {
          status: 'Production',
          row_no: 2,
          diagnosis_code: 3,
          description: 'DUMMY - TEST DIAGNOSIS',
          version: 9,
          begin_date: '04/01/1991',
          end_date: '12/31/2015',
          active: 'A',
          tmhp_flag: '',
          rc_flag: '',
          hospice_flag: '',
          dms_flag: '',
          idd_flag: '',
          comments: 'SSAS INITIAL LOAD',
          create_date: '03/22/2012',
          create_by: 'SSAS',
          update_date: '',
          update_by: '',
        },
      ],
    },
    {
      name: 'ECC - ELIGIBILITY CATEGORY',
      id: 31,
      data: [
        {
          status: 'Production',
          row_no: 1,
          'eligibility_cat._code': 1,
          description: 'OLD AGE ASSISTANCE',
          active: 'A',
          begin_date: '01/01/1900',
          end_date: '12/31/2199',
          create_date: '10/20/2007',
          create_by: 'CODETABLE',
          update_date: '01/05/1998',
          update_by: 'CODETABLE',
          comments: '',
        },
        {
          status: 'Production',
          row_no: 2,
          'eligibility_cat._code': 2,
          description: 'AFDC',
          active: 'A',
          begin_date: '01/01/1900',
          end_date: '12/31/2199',
          create_date: '10/20/2007',
          create_by: 'CODETABLE',
          update_date: '01/05/1998',
          update_by: 'CODETABLE',
          comments: '',
        },
      ],
    },
    {
      name: 'FCD - FUND CODE',
      id: 32,
      data: [
        {
          status: 'Production',
          row_no: 1,
          fund_code: '',
          description: 'DEFAULT - USE ELIG HISTORY',
          'budget_req._ind.': '',
          'medcd_req._ind.': '',
          active: 'A',
          begin_date: '01/01/1900',
          end_date: '12/31/2199',
          create_date: '10/21/2007',
          create_by: 'CODETABLE',
          update_date: '10/21/2007',
          update_by: 'CODETABLE',
          comments: '',
        },
        {
          status: 'Production',
          row_no: 2,
          fund_code: '100',
          description: '100% STATE',
          'budget_req._ind.': 'Y',
          'medcd_req._ind.': 'N',
          active: 'A',
          begin_date: '01/01/1900',
          end_date: '12/31/2199',
          create_date: '10/21/2007',
          create_by: 'CODETABLE',
          update_date: '05/19/1998',
          update_by: 'CODETABLE',
          comments: '',
        },
      ],
    },
    {
      name: 'FSR - FISCAL ACCOUNT CODE',
      id: 33,
      data: [
        {
          status: 'Production',
          row_no: 442,
          service_group: 3,
          billing_code: 99999,
          fund_code: '100',
          fiscal_year: 2008,
          agency_num: 324,
          'reg/div_code': 641,
          'app._code_cost_center': 13003,
          object_code: 71515,
          pac: 661,
          active: 'A',
          'sub_doc._type': 'S6',
          voucher_fund_code: 1,
          voucher_class_fld: 66135,
          voucher_project_id: '998_GEN_STATE',
          voucher_account: 767311,
          'voucher_dept._id': 6410000000,
          voucher_program: 661,
          begin_date: '09/01/2007',
          end_date: '08/31/2008',
          create_date: '10/22/2007',
          create_by: 'CODETABLE',
          update_date: '10/22/2007',
          update_by: 'CODETABLE',
          comments: '',
        },
        {
          status: 'Production',
          row_no: 443,
          service_group: 3,
          billing_code: 99999,
          fund_code: '19MFP',
          fiscal_year: 2008,
          agency_num: 324,
          'reg/div_code': 641,
          'app._code_cost_center': 13039,
          object_code: 71520,
          pac: 663,
          active: 'A',
          'sub_doc._type': 'S6',
          voucher_fund_code: 1,
          voucher_class_fld: 66302,
          voucher_project_id: '936_MFP_PI',
          voucher_account: 766112,
          'voucher_dept._id': 6410000000,
          voucher_program: 633,
          begin_date: '09/01/2007',
          end_date: '08/31/2008',
          create_date: '10/22/2007',
          create_by: 'CODETABLE',
          update_date: '10/22/2007',
          update_by: 'CODETABLE',
          comments: '',
        },
      ],
    },
    {
      name: 'LBR - SERVICE_RESI_LOCATION',
      id: 34,
      data: [
        {
          status: 'Production',
          row_no: 1,
          service_group: 4,
          service_code: '',
          residential_type: '6',
          begin_date: '01/01/2012',
          end_date: '12/31/2199',
          location_type: '6',
          active: 'A',
          send_to_tmhp: 'N',
          comments: 1,
        },
        {
          status: 'Production',
          row_no: 2,
          service_group: 5,
          service_code: '',
          residential_type: '',
          begin_date: '01/01/2012',
          end_date: '12/31/2199',
          location_type: '',
          active: 'A',
          send_to_tmhp: 'N',
          comments: 2,
        },
      ],
    },
    {
      name: 'LST - LEVEL OF SERVICE TYPE',
      id: 35,
      data: [
        {
          status: 'Production',
          row_no: 1,
          lvl_srvc_type_code: '20',
          description: '2060',
          active: 'A',
          begin_date: '01/01/1900',
          end_date: '12/31/2199',
          create_date: '10/21/2007',
          create_by: 'JDG',
          update_date: '10/21/2007',
          update_by: 'CODETABLE',
          comments: '',
        },
        {
          status: 'Production',
          row_no: 2,
          lvl_srvc_type_code: 'PR',
          description: 'PRIORITY',
          active: 'A',
          begin_date: '01/01/1900',
          end_date: '12/31/2199',
          create_date: '10/21/2007',
          create_by: 'JDG',
          update_date: '10/21/2007',
          update_by: 'CODETABLE',
          comments: '',
        },
      ],
    },
    {
      name: 'MSQ - MOVEMENT_SEQUENCES',
      id: 36,
      data: [
        {
          status: 'Production',
          row_no: 1,
          to_movement_code: 'CP',
          to_status: 4,
          from_movement_code: 'ADM',
          from_status: 5,
          from_purpose_code: 1,
          to_purpose_code: 2,
          service_group: 4,
          contract_check_flag: 'Y',
          hold_effective_after_days: '',
          active: 'A',
          comments: 'SSAS INITIAL LOAD',
        },
        {
          status: 'Production',
          row_no: 2,
          to_movement_code: 'DED',
          to_status: 4,
          from_movement_code: 'ADM',
          from_status: 5,
          from_purpose_code: 1,
          to_purpose_code: 2,
          service_group: 4,
          contract_check_flag: 'Y',
          hold_effective_after_days: '',
          active: 'A',
          comments: 'SSAS INITIAL LOAD',
        },
      ],
    },
    {
      name: 'PME - TMHP MUTEX',
      id: 37,
      data: [
        {
          status: 'Production',
          row_no: 1,
          service_group: 1,
          service_group_mutex: 16,
          exception_service_code: '40',
          sequence_number: 1,
          active: 'A',
          begin_date: '01/01/1900',
          end_date: '12/31/2199',
          create_date: '10/19/2007',
          create_by: 'CODETABLE',
          update_date: '10/19/2007',
          update_by: 'CODETABLE',
          comments: '',
        },
        {
          status: 'Production',
          row_no: 2,
          service_group: 1,
          service_group_mutex: 16,
          exception_service_code: '40A',
          sequence_number: 2,
          active: 'A',
          begin_date: '01/01/1900',
          end_date: '12/31/2199',
          create_date: '10/19/2007',
          create_by: 'CODETABLE',
          update_date: '10/19/2007',
          update_by: 'CODETABLE',
          comments: '',
        },
      ],
    },
    {
      name: 'REF - REFERENCE_TABLE',
      id: 38,
      data: [
        {
          status: 'Production',
          row_no: 1,
          service_grp: 4,
          service_code: '',
          'check_service_cd_/_res_type': 0,
          living_arrangement: 7,
          residential_type: '6',
          provider_location_type: '6',
          invalid_service_codes: '',
          comments: 'SSAS INITIAL LOAD',
          active: 'A',
        },
        {
          status: 'Production',
          row_no: 2,
          service_grp: 5,
          service_code: '',
          'check_service_cd_/_res_type': 0,
          living_arrangement: 6,
          residential_type: '',
          provider_location_type: '',
          invalid_service_codes: '',
          comments: 'SSAS INITIAL LOAD',
          active: 'A',
        },
      ],
    },
    {
      name: 'SGO - SRVC GRP SRVC OVERLAP',
      id: 39,
      data: [
        {
          status: 'Production',
          row_no: 1,
          service_group: 1,
          service_code: 1,
          service_group_overlap: 1,
          service_code_overlap: 1,
          overlap_type: 0,
          force: 'N',
          active: 'A',
          begin_date: '01/01/1972',
          end_date: '12/31/2199',
          create_date: '10/23/2007',
          create_by: 'JAGANNATH',
          update_date: '10/23/2007',
          update_by: 'CODETABLE',
          comments: 'JAGANNATH',
        },
        {
          status: 'Production',
          row_no: 2,
          service_group: 1,
          service_code: 1,
          service_group_overlap: 1,
          service_code_overlap: 15,
          overlap_type: 2,
          force: 'N',
          active: 'A',
          begin_date: '01/01/1972',
          end_date: '12/31/2199',
          create_date: '10/23/2007',
          create_by: 'JAGANNATH',
          update_date: '10/23/2007',
          update_by: 'CODETABLE',
          comments: 'JAGANNATH',
        },
      ],
    },
  ];
}
